[2024-02-26 21:11:55,576] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: quarta_dag.tsk3 2024-02-26T21:11:53.002340+00:00 [queued]>
[2024-02-26 21:11:55,599] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: quarta_dag.tsk3 2024-02-26T21:11:53.002340+00:00 [queued]>
[2024-02-26 21:11:55,601] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-02-26 21:11:55,601] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-02-26 21:11:55,601] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-02-26 21:11:55,627] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): tsk3> on 2024-02-26T21:11:53.002340+00:00
[2024-02-26 21:11:55,636] {standard_task_runner.py:52} INFO - Started process 60 to run task
[2024-02-26 21:11:55,642] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'quarta_dag', 'tsk3', '2024-02-26T21:11:53.002340+00:00', '--job-id', '23', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/quartadag.py', '--cfg-path', '/tmp/tmptmwa8ef5', '--error-file', '/tmp/tmp7hrb1hi9']
[2024-02-26 21:11:55,643] {standard_task_runner.py:77} INFO - Job 23: Subtask tsk3
[2024-02-26 21:11:55,731] {logging_mixin.py:109} INFO - Running <TaskInstance: quarta_dag.tsk3 2024-02-26T21:11:53.002340+00:00 [running]> on host 327ccc72d4d2
[2024-02-26 21:11:55,841] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=quarta_dag
AIRFLOW_CTX_TASK_ID=tsk3
AIRFLOW_CTX_EXECUTION_DATE=2024-02-26T21:11:53.002340+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-26T21:11:53.002340+00:00
[2024-02-26 21:11:55,843] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-02-26 21:11:55,845] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 5']
[2024-02-26 21:11:55,875] {subprocess.py:74} INFO - Output:
[2024-02-26 21:12:00,876] {subprocess.py:82} INFO - Command exited with return code 0
[2024-02-26 21:12:00,918] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=quarta_dag, task_id=tsk3, execution_date=20240226T211153, start_date=20240226T211155, end_date=20240226T211200
[2024-02-26 21:12:00,979] {local_task_job.py:151} INFO - Task exited with return code 0
[2024-02-26 21:12:01,017] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
