[2024-03-05T09:49:54.612+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hook.insert_data_task manual__2024-03-05T09:49:48.933729+00:00 [queued]>
[2024-03-05T09:49:54.644+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hook.insert_data_task manual__2024-03-05T09:49:48.933729+00:00 [queued]>
[2024-03-05T09:49:54.645+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-03-05T09:49:54.645+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-03-05T09:49:54.646+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-03-05T09:49:54.690+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): insert_data_task> on 2024-03-05 09:49:48.933729+00:00
[2024-03-05T09:49:54.700+0000] {standard_task_runner.py:55} INFO - Started process 127 to run task
[2024-03-05T09:49:54.708+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hook', 'insert_data_task', 'manual__2024-03-05T09:49:48.933729+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/hooks.py', '--cfg-path', '/tmp/tmpap8vx82x']
[2024-03-05T09:49:54.710+0000] {standard_task_runner.py:83} INFO - Job 311: Subtask insert_data_task
[2024-03-05T09:49:54.740+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-03-05T09:49:54.843+0000] {task_command.py:388} INFO - Running <TaskInstance: hook.insert_data_task manual__2024-03-05T09:49:48.933729+00:00 [running]> on host df7038a2f7dd
[2024-03-05T09:49:55.022+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hook
AIRFLOW_CTX_TASK_ID=insert_data_task
AIRFLOW_CTX_EXECUTION_DATE=2024-03-05T09:49:48.933729+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-05T09:49:48.933729+00:00
[2024-03-05T09:49:55.041+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-03-05T09:49:55.047+0000] {sql.py:375} INFO - Running statement: insert into test2 values(1);, parameters: None
[2024-03-05T09:49:55.052+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/hooks.py", line 16, in insert_data
    pg_hook.run('insert into test2 values(1);', autocommit=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "test2" does not exist
LINE 1: insert into test2 values(1);
                    ^

[2024-03-05T09:49:55.080+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=hook, task_id=insert_data_task, execution_date=20240305T094948, start_date=20240305T094954, end_date=20240305T094955
[2024-03-05T09:49:55.121+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 311 for task insert_data_task (relation "test2" does not exist
LINE 1: insert into test2 values(1);
                    ^
; 127)
[2024-03-05T09:49:55.163+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-03-05T09:49:55.275+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
