[2024-03-01 09:13:13,872] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: branchstests.gera_numero_aleatorio_task 2024-03-01T09:13:12.775828+00:00 [queued]>
[2024-03-01 09:13:13,902] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: branchstests.gera_numero_aleatorio_task 2024-03-01T09:13:12.775828+00:00 [queued]>
[2024-03-01 09:13:13,902] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 09:13:13,902] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-03-01 09:13:13,902] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 09:13:13,916] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): gera_numero_aleatorio_task> on 2024-03-01T09:13:12.775828+00:00
[2024-03-01 09:13:13,922] {standard_task_runner.py:52} INFO - Started process 133 to run task
[2024-03-01 09:13:13,930] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'branchstests', 'gera_numero_aleatorio_task', '2024-03-01T09:13:12.775828+00:00', '--job-id', '268', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/branchs.py', '--cfg-path', '/tmp/tmptj71mdgq', '--error-file', '/tmp/tmp_jnbz17b']
[2024-03-01 09:13:13,931] {standard_task_runner.py:77} INFO - Job 268: Subtask gera_numero_aleatorio_task
[2024-03-01 09:13:14,000] {logging_mixin.py:109} INFO - Running <TaskInstance: branchstests.gera_numero_aleatorio_task 2024-03-01T09:13:12.775828+00:00 [running]> on host b6da4fb5c714
[2024-03-01 09:13:14,082] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=branchstests
AIRFLOW_CTX_TASK_ID=gera_numero_aleatorio_task
AIRFLOW_CTX_EXECUTION_DATE=2024-03-01T09:13:12.775828+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-01T09:13:12.775828+00:00
[2024-03-01 09:13:14,083] {python.py:151} INFO - Done. Returned value was: 74
[2024-03-01 09:13:14,124] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=branchstests, task_id=gera_numero_aleatorio_task, execution_date=20240301T091312, start_date=20240301T091313, end_date=20240301T091314
[2024-03-01 09:13:14,186] {local_task_job.py:151} INFO - Task exited with return code 0
[2024-03-01 09:13:14,229] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
